### ISSUE TITLE
Subscribe to MailChimp Within User Registration Form

### ISSUE THREAD

**Issue by challahan** [aelvan/mailchimp-subscribe-craft#110]
Does the plugin author or anyone else have an example or sample code for integration MailChimp sign up into a user registration form.

It looks like a form cannot have multiple actions (ie users/save-user and mailchimp-subscribe), so some kind of custom controller plugin would need to be written. Any examples would be much appreciated as I've not done this before!

**Comment by mmikkel** [comment]
You'd probably need to write a custom module that listens for the appropriate [event](https://craftcms.com/docs/3.x/extend/events.html) when a user is created, and subscribes that user via MailChimp Subscribe's [`subscribe()`](https://github.com/aelvan/mailchimp-subscribe-craft/blob/craft3/src/services/MailchimpSubscribeService.php#L47) method.
