### ISSUE TITLE
API response

### ISSUE THREAD

**Issue by olsp** [aelvan/mailchimp-subscribe-craft#112]
Hi!
I implemented the form with the plugin on a website and have a question regarding the API response. 
When I enter my email address I don't get any response at all. I tried it via the API without craft/your plugin and then get the resonse, that the address is already added to the list.
Is there a way to get this response via the plugin as well? When I check if mailchimpSubscribe is defined, this is false.

**Comment by architchandra** [comment]
Even I'm facing an issue where `mailchimpSubscribe` is not defined. Why might this be happening?

Mailchimp Subscribe version: `3.0.3`
Craft version: `3.4.30`
PHP version: `7.4.19`

Update: The `mailchimpSubscribe` showed up when I submitted a response. I was expecting it to exist on the page by default.
