### ISSUE TITLE
Multi List Subscription Not Working

### ISSUE THREAD

**Issue by lettie16** [aelvan/mailchimp-subscribe-craft#12]
I'm having an issue with the multilist subscription.
Everything is fine up until the foreach statement:

    foreach ($listIdArr as $listId) {
         $retval = $api->listSubscribe($listId, $email, $vars);
    }

print_r($listIdArr) before it reveals an array created from the piped string which is correct. However the above only seems to subscribe the user to the last list in the array? Any ideas or how to fix?

Cheers

Quick Edit on this. It seems the problem only occurs if the FNAME or LNAME variables are empty.

**Comment by aelvan** [comment]
I've tested this, and it works both with and without FNAME/LNAME, I'm signed up to both lists.
