### ISSUE TITLE
An error occured when trying to subscribe email - Invalid Resource (400)

### ISSUE THREAD

**Issue by wrapper** [aelvan/mailchimp-subscribe-craft#120]
Hey there

I have a site configured with the default settings listed on the readme page. I believe it was working on a previous version of Craft, however I now get a 400 error when trying to subscribe.

Would love some help!

**Comment by rrr3da** [comment]
Same for us. We just downgraded from 3.1.0 (faulty) to 3.0.3 and things are working as expected.

Log taken from web.log:

`
2021-11-08 16:39:57 [-][-][-][error][aelvan\mailchimpsubscribe\services\MailchimpSubscribeService::getInterestGroups] An error occured when trying to get list interests: The requested resource could not be found.
2021-11-08 16:39:57 [-][-][-][error][craft\elementapi\controllers\DefaultController::actionIndex] Error resolving Element API endpoint: Invalid argument supplied for foreach()
2021-11-08 16:39:57 [-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /home/customer/*************/vendor/aelvan/mailchimp-subscribe/src/services/MailchimpSubscribeService.php:783

Stack trace:

#0 /home/customer/*************/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/home/customer/...', 783)

#1 /home/customer/*************/vendor/aelvan/mailchimp-subscribe/src/services/MailchimpSubscribeService.php(783): craft\web\ErrorHandler->handleError(2, 'Invalid argumen...', '/home/customer/...', 783, Array)

#2 /home/customer/*************/vendor/aelvan/mailchimp-subscribe/src/services/MailchimpSubscribeService.php(80): aelvan\mailchimpsubscribe\services\MailchimpSubscribeService->prepInterests('*******', Array)

#3 /home/customer/*************/config/element-api.php(214): aelvan\mailchimpsubscribe\services\MailchimpSubscribeService->subscribe('red**********@***...', '*******', Array)
`

**Comment by wrapper** [comment]
Ah, I tried downgrading to 3.0.3 and still have the same issue. I don't think we have the same problem.

Here's my log message

`2021-11-10 12:54:59 [-][-][-][error][aelvan\mailchimpsubscribe\services\MailchimpSubscribeService::subscribe] An error occured when trying to subscribe email `email@email.com`: Invalid Resource (400)
`

**Comment by carolineboeykens** [comment]
Is there any news on this issue? We're a little bit stuck with this bug.

**Comment by mmikkel** [comment]
Based on the stack trace from @rrr3da, I believe this is the same issue as #122, which is fixed in the latest release (3.1.1.1). Have you tried upgrading to that version?

**Comment by carolineboeykens** [comment]
Yes, it is fixed now! Thank you!

**Comment by mmikkel** [comment]
@carolineboeykens Great, thanks for the follow-up!

**Comment by rrr3da** [comment]
3.1.1.1 is working for us, too.
Thank you guys
