### ISSUE TITLE
getInterestGroups returning as NULL.

### ISSUE THREAD

**Issue by JamsRepos** [aelvan/mailchimp-subscribe-craft#122]
Hi,

I am currently trying to pull interest groups to loop through and add checkboxes as per the usage [docs](https://github.com/aelvan/mailchimp-subscribe-craft#usage) and it seems the `craft.mailchimpSubscribe.getInterestGroups()` is returning back null with both the audience specified as a param or inside the `mailchimp-subscribe.php` config. 

Is functionality currently not working or is there something I am doing wrong? 

Thanks.

**Comment by mmikkel** [comment]
Hi @LubricantJam,

Which version of MailChimp Subscribe are you using?

**Comment by JamsRepos** [comment]
> Hi @LubricantJam,
> 
> Which version of MailChimp Subscribe are you using?

3.1.1. Just noticed the new version, is this a fix for this method?

**Comment by mmikkel** [comment]
Yep, the problem should be fixed in 3.1.1.1 via https://github.com/aelvan/mailchimp-subscribe-craft/commit/5e1e147d6a5be306bbd68ae112f3d5407fe357b2. Could you try updating and let me know if it resolves the issue?

**Comment by JamsRepos** [comment]
> Yep, the problem should be fixed in 3.1.1.1 via [5e1e147](https://github.com/aelvan/mailchimp-subscribe-craft/commit/5e1e147d6a5be306bbd68ae112f3d5407fe357b2). Could you try updating and let me know if it resolves the issue?

Appears to be! Sorry, I noticed the recent commits but didn't think to take a look. Cheers for that!

**Comment by mmikkel** [comment]
No probs! I was worried about there possibly being a regression error here, which is why I asked :) Happy it's sorted, thank you for the follow-up.
