### ISSUE TITLE
Guzzle 7.x

### ISSUE THREAD

**Issue by vaileamon** [aelvan/mailchimp-subscribe-craft#124]
Hi guys !
I have a guzzle dependency conflit between mailchimp-subscribe-craft (requires guzzle 6.x) and craftcms/commerce-multisafepay (requires guzzle 7.x).
Is it an easy option to update to 7.x ?
Thanks for the feedback !

**Comment by masiorama** [comment]
Hello @ineghi did you close the issue because ...? I am having the same problem, so I am wondering how to fix it, since I cannot install the package via composer install. Thanks!

**Comment by ademers** [comment]
I'm having a similar issue. In my case the Guzzle version conflict is preventing me from updating the [Mailgun](https://github.com/craftcms/mailgun) & [Notifications](https://github.com/percipioglobal/craft-notifications) plugins on Craft 3.7.48.

I understand that the plugin is discontinued for Craft 2.x, but I'm not able to upgrade this particular site to Craft 4.x just yet. Thanks!

**Comment by mmikkel** [comment]
> I'm having a similar issue. In my case the Guzzle version conflict is preventing me from updating the [Mailgun](https://github.com/craftcms/mailgun) & [Notifications](https://github.com/percipioglobal/craft-notifications) plugins on Craft 3.7.48.

MailChimp Subscribe has been compatible with Guzzle 7 for [a good while](https://github.com/aelvan/mailchimp-subscribe-craft/commit/b9c55ac27af35db54d0028790d7108fb45554a81#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R26), so this is likely a Composer dependency issue.

Try adding the `-w` flag to the failing `composer update` command, i.e. `composer update -w`.

**Comment by ademers** [comment]
I see what's going on now. I'm running 3.0.3 which has`"pacely/mailchimp-apiv3": "^1.0"` as a dependency which in turn depends on an older version of Guzzle. However, the latest version is actually 3.1.1.1 (with dep as `"guzzlehttp/guzzle": "^6.5.5|^7.2.0" instead` but for some reason I did not see a notice in the Craft CP asking me to update to 3.1.1.1. So, updating to 3.1.1.1 solved the issue, but still find it odd that I didn't see latest version in the CP. https://share.cleanshot.com/SAKNZlzTMBraBSL0tqCv

**Comment by aelvan** [comment]
Since the plugin has been removed from the store, it will no longer show up in that list.
