### ISSUE TITLE
Under which license is this project distributed?

### ISSUE THREAD

**Issue by ryuslash** [aelvan/mailchimp-subscribe-craft#18]
Hi,

I don't see a `LICENSE` or `COPYING` file in the project and I don't see any mention of a license in the readme or the plugin file. Which license is this project supposed to be distributed under?

Could you please provide some clarification and add either file mentioned?

Thanks in advance.

**Comment by ryuslash** [comment]
I see a license has just been added to the project, thank you very much for your help.

**Comment by aelvan** [comment]
Yeah, I added a MIT license to it. :)

**Comment by ryuslash** [comment]
Thank you :)
