### ISSUE TITLE
Does this work for Craft 2.5 ?

### ISSUE THREAD

**Issue by Chrisedmo** [aelvan/mailchimp-subscribe-craft#19]
Im trying to integrate this plug in as basic as possible and its not working. Im just getting a "An error occured. Please try again." error.

I used the 2nd example from your ready file.

I wonder if it's an issue with Craft 2.5

**Comment by mdxprograms** [comment]
if I ```dump(mailchimpSubscribe)``` I keep getting invalid email

**Comment by aelvan** [comment]
I've tested it in Craft 2.5 now, and it works just fine. 

@Chrisedmo Can you try to do dump(mailchimpSubscribe) in your template and see what's returned.

@mdxprograms What's the email you're trying to subscribe? :)

**Comment by mdxprograms** [comment]
I got it fixed. I realized I was using the mcvar to include the email field in the POST instead of just using "email" for the name attribute. Thanks!
