### ISSUE TITLE
Parse error on install

### ISSUE THREAD

**Issue by darylknight** [aelvan/mailchimp-subscribe-craft#21]
I just installed this on a site running Craft 2.5.2762 and I get the following error:

`Parse error: syntax error, unexpected '[', expecting ')' in /Users/username/Sites/sitename.dev/craft/plugins/mailchimpsubscribe/vendor/guzzlehttp/promises/src/functions.php on line 41`

**Comment by aelvan** [comment]
Which PHP version are you running?

**Comment by darylknight** [comment]
Ah my mistake, I'd left MAMP running in 5.3.29 when I was trying to test something on another site. It works on all other versions - Thanks!
