### ISSUE TITLE
Property of a non-object - $result

### ISSUE THREAD

**Issue by nealstammers** [aelvan/mailchimp-subscribe-craft#22]
Hi, When submitting a form request an error is thrown: 

MailchimpSubscribe_ListController : line 39

$result->success

($result is an array) $result['success'] works correctly.

Hopefully resolved https://github.com/aelvan/mailchimp-subscribe-craft/pull/23

**Comment by aelvan** [comment]
Not seeing this error. I've tested with PHP 5.5 (which is the current minimum because of the guzzle version used), 5.6 and 7.0.
