### ISSUE TITLE
500 error from Mailchimp...

### ISSUE THREAD

**Issue by spotd** [aelvan/mailchimp-subscribe-craft#26]
I have the correct api details and list id, goes to 500 error?

**Comment by spotd** [comment]
Actually looks like another site which which was working with this plugin is also now broken with the latest craft build

**Comment by aelvan** [comment]
Which error message does Craft return if you set devMode to true?

**Comment by aelvan** [comment]
I've tested the plugin on the latest Craft build now, and it appears to be working just fine. Please provide som more information on how you have things set up, and what error message that is being returned.

**Comment by spotd** [comment]
Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /homepages/29/d614166137/htdocs/bizutd/craft/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

**Comment by aelvan** [comment]
Which php version are you running?

**Comment by spotd** [comment]
5.4.45

**Comment by spotd** [comment]
Ok updated to 5.6 and works again! Thank you for the pointer
