### ISSUE TITLE
Error: Trying to get property of non-object

### ISSUE THREAD

**Issue by bgarrant** [aelvan/mailchimp-subscribe-craft#28]
I added this to another post but figured we better open a new one. 

I am getting this error on line (line 090).Received error in PHP 7 and 5.6

Trying to get property of non-object

![capture](https://cloud.githubusercontent.com/assets/2436728/15796399/ead71ad8-29ca-11e6-953e-0c70f740536c.jpg)

**Comment by bgarrant** [comment]
Here is entire page:

![fireshot screen capture 034 - php notice - ubuale_dev_newsletter-signup](https://cloud.githubusercontent.com/assets/2436728/15796419/36102986-29cb-11e6-8164-f65d1b93da45.png)

**Comment by aelvan** [comment]
I've tested in both PHP 7.0 and 5.6, and I'm not able to reproduce the error. Could you try to add:

`Craft::dd($e->getMessage())`

...before line 89 in MailchimpSubscribeService.php, and let me know what that outputs?

**Comment by bgarrant** [comment]
Hello and thanks for quick response.  It seems to be working now but it does not have any validation for making fields required.  Any idea how I can make the FNAME, LNAME and EMAIL fields required from the example code on your plugin page?

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159

**Comment by aelvan** [comment]
Yeah, only the email address is validated, since that's the only required parameter in the api. You'd either have to do it with javascript and/or html5 properties in the front-end, or make your own plugin with a controller that do the validation, and then uses the service from this plugin to do the subscribe.

**Comment by bgarrant** [comment]
I tried this code to make the three fields required and it does not work.  Can you help?  I just want to make sure people fill them before submit as there is no message indicating the error.

 

```

    {% macro errorList(errors) %}

    {% if errors %}

        <ul class="errors">

            {% for error in errors %}

                <li>{{ error }}</li>

            {% endfor %}

        </ul>

    {% endif %}

    {% endmacro %}

 

    {% from _self import errorList %}

 

    <form class="newsletter-form" action="" method="POST">

      <input type="hidden" name="action" value="mailchimpSubscribe/list/Subscribe">

      <input type="hidden" name="lid" value="e1dbacd8f9">

 

      {% if mailchimpSubscribe is defined %}

        {% if (not mailchimpSubscribe.success) and (mailchimpSubscribe.errorCode!='1000') %}

          <p>An error occured. Please try again.</p>

        {% endif %}

 

        {% if mailchimpSubscribe.success %}

          <p>Thank you for signing up!</p>

        {% endif %}

      {% endif %}

 

      <div class="field-line">

        <label>First name:</label>

        <input type="text" name="mcvars[FNAME]" value="{% if (mailchimpSubscribe is defined) and (not mailchimpSubscribe.success) %}{{ mailchimpSubscribe.values.vars.FNAME }}{% endif %}"/>

         {{ mailchimpSubscribe is defined and mailchimpSubscribe ? errorList(mailchimpSubscribe.getErrors('mcvars[FNAME]')) }}

      </div>

 

      <div class="field-line">

        <label>Last name:</label>

        <input type="text" name="mcvars[LNAME]" value="{% if (mailchimpSubscribe is defined) and (not mailchimpSubscribe.success) %}{{ mailchimpSubscribe.values.vars.LNAME }}{% endif %}"/>

        {{ mailchimpSubscribe is defined and mailchimpSubscribe ? errorList(mailchimpSubscribe.getErrors('mcvars[LNAME]')) }}

      </div>

 

      <div class="field-line">

        <label{% if (mailchimpSubscribe is defined) and (mailchimpSubscribe.errorCode=='1000') %} class="error"{% endif %}>Email:</label>

        <input type="text" name="email" value="{% if (mailchimpSubscribe is defined) and (not mailchimpSubscribe.success) %}{{ mailchimpSubscribe.values.email }}{% endif %}"/>

        {{ mailchimpSubscribe is defined and mailchimpSubscribe ? errorList(mailchimpSubscribe.getErrors('email')) }}

      </div>

 

      <input type="submit" name="" class="btn btn-default" value="Subscribe"/>

    </form>

```

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159

**Comment by bgarrant** [comment]
I just added the “required” to the form inputs and it works perfectly now.  Thanks.

 

      <div class="field-line">

        <label>First name:</label>

        <input type="text" name="mcvars[FNAME]" value="{% if (mailchimpSubscribe is defined) and (not mailchimpSubscribe.success) %}{{ mailchimpSubscribe.values.vars.FNAME }}{% endif %}" required/>

      </div>

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159
