### ISSUE TITLE
Using group with radio buttons

### ISSUE THREAD

**Issue by samlous** [aelvan/mailchimp-subscribe-craft#29]
Hi,

I'm having trouble adding Groups.
I've made a group in mailchimp that has some choises (radio buttons).
For some reason it gives me a error (Invalid Resources).

My input field for a single radio button looks like this:

`<input type="radio" name="mcvars[group][4973]['First Choice']" value="First Choice">`

Here is 4973 my from id and "First Choise"  one of the options.

Could u guys tell me what I'm doing wrong? Maybe add some more documentation about using Groups?

**Comment by samlous** [comment]
I fixed it by changing [group] to [interests]. I think GROUPINGS isn't supported anymore in Mailchimp v3.0. You have to use [interests].

For example:
<input type="radio" name="mcvars[interests][788343fc9f]" value="788343fc9f">

The string behind [interests] is the interest ID. 

I tried to get this too work with radio buttons, but radio buttons are not treated as Interests. So I had to use checkboxes.

You guys should edit the documentation about these GROUPINGS.

**Comment by aelvan** [comment]
Ok, I'll have a look at it when I get the time. Both support for groupings and interests where added by other contributors, I've never actually used either when dealing with MailChimp.

**Comment by gordan43dom** [comment]
Hello, 
I second this, groups do not work , and you have to patch adding to a interest group of a list with the ID of that group. That is the only ID you need and not the one of the list .

**Comment by aelvan** [comment]
The group functionality has been fixed/changed in 1.1.0, see new example in docs.
