### ISSUE TITLE
No response from mailchimp with new version

### ISSUE THREAD

**Issue by migswd** [aelvan/mailchimp-subscribe-craft#31]
Hi André. 
Thank you for this great plugin.
I am using V0.4 and I tried to update to V1.4 but it does not work with the new version (it works locally but not on my server).
I checked in the logs but nothing.
Where should I tried to look at ?

**Comment by aelvan** [comment]
Which php version are you running on you server? The new api library
requires php 5.5.

25. jul. 2016 13.15 skrev "Miguel Bocquier" <notifications@github.com>:

**Comment by migswd** [comment]
OK thats it !
Thanks.

Miguel
