### ISSUE TITLE
Update MailChimp API client to V3

### ISSUE THREAD

**Issue by tiborsaas** [aelvan/mailchimp-subscribe-craft#34]
From the API documentation:

"Prior versions will no longer be supported after 2016, so all API users should begin transitioning to v3.0."

**Comment by aelvan** [comment]
Mailchimp Subscribe has been using the v3.0 api since january.

**Comment by tiborsaas** [comment]
Thanks, good to know. I just checked the `MCAPI.class.php` and it said v1.3

**Comment by aelvan** [comment]
Ah, seems like I forgot to delete the old library. :) Using https://github.com/pacely/mailchimp-api-v3 now.
