### ISSUE TITLE
Error message translation

### ISSUE THREAD

**Issue by migswd** [aelvan/mailchimp-subscribe-craft#36]
Hello. Thank you for this great plugin. All works fine except the translation of messages.
How could I translate this error message see image attached
![image](https://cloud.githubusercontent.com/assets/3531623/18244536/d198b1f0-7360-11e6-8c97-bd1c02bec3a4.png)

I tried to put it in the Craft translation file but it does nothing.

**Comment by aelvan** [comment]
Not sure how to translate that, because I can't find that exact message in the code anywhere. Sure you haven't put that into your JS or templates yourself?

**Comment by migswd** [comment]
OK yes sorry the real message from your plugin is the first part : Invalid email

I am adding this at the end indeed : . Please try again.


========

Invalid email. Please try again.
$(".form-response .error").html(data.message+". Please try again.").show();

**Comment by aelvan** [comment]
The "Invalid email" message is output through the translation filter, so you should be able to translate it with Craft's normal translation functionality.

**Comment by migswd** [comment]
I did it but does not work :
"Invalid email" => "Email incorrect", // does not work

(All my other translations work fine…)

**Comment by aelvan** [comment]
I've tested this now, and it works for me. Are you sure you have the translations in the right locale, and are viewing the appropriate locale?
