### ISSUE TITLE
object given array required

### ISSUE THREAD

**Issue by bbm-buunk** [aelvan/mailchimp-subscribe-craft#38]
`array_push() expects parameter 1 to be array, object given`

`     try {
                        $results = $mc->request('lists/' . $listId . '/members/' . md5(strtolower($email)), $postVars, 'PUT');
                        array_push($results, $this->_getMessage(200, $email, $vars, Craft::t("Subscribed successfully"), true));
                    } catch (\Exception $e) { // an error occured
                        $msg = json_decode($e->getMessage());
                        array_push($results, $this->_getMessage($msg->status, $email, $vars, Craft::t($msg->title)));
                    }`

in the try part i got an error array required object given in array push

**Comment by BBMBuunk** [comment]
and if i change  `try { $results = ` to `try { $results[] = ` it gives me `Undefined index: success`

**Comment by aelvan** [comment]
What PHP version are you running?

**Comment by BBMBuunk** [comment]
Php 5.6 , but now running 7.0.x 
It looks that in the service i got no response from mailchimp (empty result) but filled in API and list key. Something to do with curl certificate?

**Comment by BBMBuunk** [comment]
It looks like the service of subscribe is calling the vendor who needs an array but object is given and the resultaat is not being added to the array because its empty.

Never the less, i got a result of succes back with some code adjustments, but it gives an unindentied index of success back.
