### ISSUE TITLE
One mailing list ID by site locale

### ISSUE THREAD

**Issue by dredumont** [aelvan/mailchimp-subscribe-craft#40]
I have this common problem that MailChimp doesn't send email confirmation (ex.: double opt-in) regarding the user language. So, to get around this problem, I must create a mailing list by language and set the "lid" field with a custom variable in the settings.

I was wondering if this could be an appropriate feature to display one mailing list ID field for each site locale in the control panel if the site is localized ? See the image attached.

Thanks !

![ss](https://cloud.githubusercontent.com/assets/9426205/25142066/a049563e-2433-11e7-8147-8109ff5424aa.png)

**Comment by aelvan** [comment]
You can easily supply different list id's pr language in the template by adding a hidden list id field with different values pr language. See documentation for example.
