### ISSUE TITLE
Example of "Ajax submitting" is not working properly

### ISSUE THREAD

**Issue by outline4** [aelvan/mailchimp-subscribe-craft#42]
I think there are a bunch of errors relating to the recent update of the plugin.   
I had version 0.4 installed and it worked much better than the new one...

This example does not seem to work:  
https://github.com/aelvan/mailchimp-subscribe-craft#ajax-submitting

It always outputs "WEEEEEEEEE"...   
Before the update it worked like a charm and was submitting the correct error codes! E.G. Also the codes that a user was already subscribed. 
Now it's all WEEEEEEEEE but does not work :(

**Comment by daltonrooney** [comment]
I'm testing the latest version 1.1.3 and I can confirm that the ajax-submitting example is working OK. You might have something else going on.

**Comment by outline4** [comment]
Hm? (⊙_☉) 
I'll investigate tomorrow...  
Thanks

**Comment by daltonrooney** [comment]
I did have a problem when I moved from development to staging, though. I was getting a 400 error with the form on staging even though it was working fine in development. Turns out it was a CSRF error, which was not enabled in the dev config.

**Comment by outline4** [comment]
Sorry, that I am picking up the issue again:  
So if you put in a wrong email address, it sends the data.message correctly.  
But if you specify an email address that already exists, it won't warn you like it did before.  

What could I check to narrow down the issue I am having?

**Comment by telesma** [comment]
Had the same problem. Csrf-protection was set to true in config/general.php

Take a look how to set up your form:
[https://craftcms.com/support/csrf-protection](https://craftcms.com/support/csrf-protection)
