### ISSUE TITLE
Check if api key and list id is populated

### ISSUE THREAD

**Issue by alexcarpenter** [aelvan/mailchimp-subscribe-craft#46]
Is there a way to check if the api key and list id is populated to show the newsletter form?

```
{% if mailchimpSubscribe is defined %}
    {% include '_components/newsletter' %}
{% endif %}
```

**Comment by aelvan** [comment]
Yes, the settings is part of Crafts config, so to check for the API key for instance, you'd do: `craft.config.mcsubApikey`.
