### ISSUE TITLE
404

### ISSUE THREAD

**Issue by jnaklaas** [aelvan/mailchimp-subscribe-craft#48]
I'm having a hard time getting this plugin to work, using the example code.

I'm on craft 2.6.3000, and using the master branch of the plugin.

```
<form class="newsletter-form" id="newsletter-form" action="" method="POST">
            {{ getCsrfInput() }}
                <input type="hidden" name="action" value="mailchimpSubscribe/list/Subscribe">
                <input type="hidden" name="redirect" value="{{siteUrl}}#newsletter-form">

                {% if mailchimpSubscribe is defined %}

                    <p>{{mailchimpSubscribe.errorCode}} - {{mailchimpSubscribe.message}}</p>

                {% endif %}

                <div class="field-line">
                <label{% if (mailchimpSubscribe is defined) and (mailchimpSubscribe.errorCode=='1000') %} class="error"{% endif %}>Email:</label>
                <input type="text" name="email" value="{% if (mailchimpSubscribe is defined) and (not mailchimpSubscribe.success) %}{{ mailchimpSubscribe.values.email }}{% endif %}"/>
                </div>

                <input type="submit" name="" value="Subscribe"/>
            </form>
```

When submitting the empty form or an invalid email, I'm getting errorCode `1000` and message ` Invalid email` (as it should).

When submitting the form with a valid email, I'm getting errorCode `404` and message `Resource Not Found`.

On a side note, I would like to scroll the page to the form after submitting, since the form is located at the bottom of the homepage, hence the `<input type="hidden" name="redirect" value="{{siteUrl}}#newsletter-form">`. As the redirect is only supposed to work when having a successful subscription, how can I have the correct scrollposition when having an error?

**Comment by Stenvdb** [comment]
For what its worth, I've had the exact same response you're mentioning. For me the error was a wrong list id. Don't use the id as shown in the url in MailChimp, instead go to list > settings> list name and defaults. Noticed this thanks to: https://github.com/drewm/mailchimp-api/issues/75#issuecomment-293134838
