### ISSUE TITLE
Automatically check if email on list (Craft 2.x version)

### ISSUE THREAD

**Issue by ademers** [aelvan/mailchimp-subscribe-craft#50]
Is there a way to check if an email is on a list without having to click the `Check if subscribed` button as per the example form documented at https://github.com/aelvan/mailchimp-subscribe-craft/tree/master#checking-if-an-email-is-already-on-a-list?

I noticed that the Craft 3 version has this alternative:
```
{% set checkResponse = craft.mailchimpSubscribe.checkIfSubscribed('email@domain.com', 'mylistid') %}

{% if checkResponse.success %}
    Email is on list!
{% else %}
    Email is NOT on list!
{% endif %}
```
Would the above be possible in the Craft 2.x version? If not, could you suggest any workarounds?

**Comment by aelvan** [comment]
Myeah, there wasn't a template variable in the Craft 2 version, I added it when I upgraded it to Craft 3. There is a controller action though, so you could do an ajax call and show/not show the subscribe form based on the response, see: 

https://github.com/aelvan/mailchimp-subscribe-craft/tree/master#checking-if-an-email-is-already-on-a-list

It's a bit clunky. Alternatively, there is a service method in the Craft 2 version, so you could make your own template variable (either in a business logic plugin or add it to the plugin and send me a PR), and access the service like this:

```
$result = craft()->mailchimpSubscribe->checkIfSubscribed($email, $listId)
```

**Comment by ademers** [comment]
It looks like I got it if working as follows. I'll create a pull request for you to review.

In `variables/MailchimpSubscribeVariable.php`, I added:
```
public function checkIfSubscribed($email, $formListId)
{
    return craft()->mailchimpSubscribe->checkIfSubscribed($email, $formListId);
}
```

And in my Craft template:

```
{% set checkResponse = craft.mailchimpSubscribe.checkIfSubscribed('email@domain.com', 'mylistid') %}

{% if checkResponse.success %}
    Email is on list!
{% else %}
    Email is NOT on list!
{% endif %}
```
