### ISSUE TITLE
Where has the craft 2 version gone?

### ISSUE THREAD

**Issue by lettie16** [aelvan/mailchimp-subscribe-craft#52]
I am currently using the craft 2 version of this plugin and we are upgrading the server to php7. However the plugin breaks with the following error message:

> Methods with the same name as their class will not be constructors in a future version of PHP; MCAPI has a deprecated constructor

I had a play around with the plugin to see if changing the function name or class name would have any effect but it through another error saying it could not connect.

So my question is do you have an archived craft 2 version with a fix in it for php 7 as we won't be switching to craft 3 just yet.

Cheers

**Comment by aelvan** [comment]
The craft 2 version is in the [master branch](https://github.com/aelvan/mailchimp-subscribe-craft/tree/master).

What version of PHP 7 are you running? Been using the plugin with PHP 7 for quite a while and haven't come across that error. Might be that I don't have deprecation errors on though.

**Comment by lettie16** [comment]
PHP 7.0.0
