### ISSUE TITLE
Not working on Craft 2 anymore

### ISSUE THREAD

**Issue by moyger** [aelvan/mailchimp-subscribe-craft#54]
Suddenly, the plugin is not working on Craft 2 anymore. I downloaded the craft 2 version in the master branch, but still can't make it work. There are no errors, it's sending the proper success response but I just don't receive the opt-in mailchimp email. 

Anyone have an idea?

**Comment by drieshooghe** [comment]
Having the same issue with the C2 master.
No errors, but not receiving any emails either.

**Comment by alexcarpenter** [comment]
@aelvan This is also not working for me anymore. Everything seems to be submitting properly but they are not getting added to my list.
