### ISSUE TITLE
Feature request: Unsubscribe from list

### ISSUE THREAD

**Issue by builtbybrad** [aelvan/mailchimp-subscribe-craft#61]
Is there anyway you could add the ability to unsubscribe a user from a list? We're wanting to add a "Marketing preferences" section to our frontend user section which will let people opt in or out of our mailchimp list.

**Comment by engram-design** [comment]
[PR #69](https://github.com/aelvan/mailchimp-subscribe-craft/pull/69) adds this.

**Comment by aelvan** [comment]
v2.0.3 adds an unsubscribe controller action. Thanks, @engram-design.

**Comment by Moorst** [comment]
Is there any documentation on this? Assuming it's something like this?

```
{% set checkResponse = craft.mailchimpSubscribe.checkIfSubscribed('email@domain.com', 'mylistid') %}
{% if checkResponse.success %}
                    
    <form method="post" accept-charset="UTF-8">
        {{ csrfInput() }}
        <input type="text" name="email" value="email@domain.com">
        <input type="hidden" name="action" value="mailchimp-subscribe/list/unsubscribe">
        <button type="submit">Unsubscribe</button>
    </form>

{% else %}

    <form method="post" accept-charset="UTF-8">      
        {{ csrfInput() }}
        <input type="hidden" name="action" value="mailchimp-subscribe/list/subscribe">...
```

Also, is it possible to use the same `mailchimp-subscribe/list/subscribe` option to update an existing subscription?

**Comment by johnj24** [comment]
@Moorst did you find a solution for unsubscribing? Using the `mailcimp-subscribe/list/unusubscribe` action continually errors-out for me.

**Comment by engram-design** [comment]
@johnj24 What's the error?

**Comment by Moorst** [comment]
I believe the above worked, though there were some bugs in the code at the time, see https://github.com/aelvan/mailchimp-subscribe-craft/issues/71. I believe these have been fixed now though
