### ISSUE TITLE
Example Hash Filter appears incorrectly

### ISSUE THREAD

**Issue by wguldin** [aelvan/mailchimp-subscribe-craft#66]
Not a huge deal, but I thought it might save someone some troubleshooting. In the main example you have: 

```
value="{{ newsletter/receipt | hash }}"
```

For the redirect. It looks like though that the hash filter takes a string. At least this was erroring for me, and this worked: 

```
value="{{ 'newsletter/receipt' | hash }}"
```

Thank you so much for this awesome tool!

**Comment by aelvan** [comment]
Thanks, that was a typo. Fixed.
