### ISSUE TITLE
Bug in check if subscribed

### ISSUE THREAD

**Issue by bossanova808** [aelvan/mailchimp-subscribe-craft#67]
https://github.com/aelvan/mailchimp-subscribe-craft/blob/2c9bf78fd414ad15e4bbdcda44863da2ba77c5a7/src/services/MailchimpSubscribeService.php#L130

This line needs to be:
`$listIdStr = $formListId !== '' ? $formListId : $settings->listId;`

...as per the subscribe service.  Otherwise the listId from settings is not used...

(also I note the docs on this are using the old action name still - `input type="hidden" name="action" value="mailchimpSubscribe/list/CheckIfSubscribed`

Seems too trivial to PR it but let me know if you want me to!

**Comment by fantasticmachine** [comment]
In addition to this I'm getting a 404 error - 
Unable to resolve the request "mailchimpSubscribe/list/CheckIfSubscribed".

**Comment by bossanova808** [comment]
@fantasticmachine That will be the whole Craft 2 to Craft 3 change in case thing - `check-if-subscribed` etc - if you follow the new rules it does work...

**Comment by engram-design** [comment]
@bossanova808 Added this is https://github.com/aelvan/mailchimp-subscribe-craft/pull/69, but also changed the function so its actually checking whether the user is subscribed, not just whether they exist on the list.

**Comment by aelvan** [comment]
Fixed in v2.0.3. Thanks, @engram-design.
