### ISSUE TITLE
[Question] XMLHttpRequest

### ISSUE THREAD

**Issue by 23d1** [aelvan/mailchimp-subscribe-craft#70]
How would one go about ajaxifying mailchimp-subscribe-craft using vanilla JS? For some reason I can't get it to work properly (400 Bad Request), even though I'm submitting with POST and json header the exact same string as when using JQuery ajax... Javascript keeps kicking my ass.

**Comment by aelvan** [comment]
A "400 Bad Request" in Craft is usually due to a missing CSRF token. Anyway, doesn't sound like a plugin error, and I'm by no means a vanilla javascript expert, so..
