### ISSUE TITLE
Couple of Unsubscribe controller bugs

### ISSUE THREAD

**Issue by Moorst** [aelvan/mailchimp-subscribe-craft#71]
The actionUnubscribe() should be;
actionUn**s**ubscribe()
(line 83 in \src\controllers\ListController.php)

Same function is missing the $redirect variable;
$redirect = $request->getParam('redirect', '');
(line ~91 in \src\controllers\ListController.php).

**Comment by aelvan** [comment]
This has been fixed in v2.0.4.
