### ISSUE TITLE
FR: Add GDPR lists support

### ISSUE THREAD

**Issue by shornuk** [aelvan/mailchimp-subscribe-craft#73]
Hi, 

Mailchimp has now made setting the dedicated GDPR fields through the API. (Better late than never!)
Is this something that can be added? 
The API shows that you need to pass your GDPR options as an array like so
```
'marketing_permissions' => [
   ['marketing_permission_id' =>'listId','enabled' => true/false],
   ['marketing_permission_id' =>'listId','enabled' => true/false],
   ['marketing_permission_id' =>'listId','enabled' => true/false}
]
```
Whereby each one represents a different GDPR list. Would be great if the plugin could pull out any `$vars` set to `marketing_permissions` and set them accordingly.  👍

[Mailchimp](
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/)

**Comment by aelvan** [comment]
This was added in v3.0.0. Alot has changed, so make sure you read the changelog and new readme before updating.
