### ISSUE TITLE
Not working with PHP 7.2

### ISSUE THREAD

**Issue by tomfischerNL** [aelvan/mailchimp-subscribe-craft#74]
Dear André,

MailChimp subscribe is not working on our PHP 7.2 environment with Craft 2. (See attachment)
With Craft 3 there are no errors, but we are not migrating all our project directly to Craft 3.
 
Are there any plans to fix this issue?

Thanks in advance.

![schermafbeelding 2019-03-06 om 12 22 34](https://user-images.githubusercontent.com/2330195/53877886-a4307300-400a-11e9-9683-f2b6d1be5eaa.png)

**Comment by aelvan** [comment]
PR #78 should fix this.
