### ISSUE TITLE
Unsubscribe action not working

### ISSUE THREAD

**Issue by Moorst** [aelvan/mailchimp-subscribe-craft#76]
Not sure if this is due to an update to MailChimps API as I'm sure this was working when I last tested a couple of months ago;

```
<form method="post" accept-charset="UTF-8">
{{ csrfInput() }}
<input type="hidden" name="email" value="{{ currentUser.email }}">
<input type="hidden" name="action" value="mailchimp-subscribe/list/unsubscribe">
<button type="submit">Unsubscribe</button>
</form>

```
I get the following error;

![image](https://user-images.githubusercontent.com/6151408/55120239-04d43c80-50ed-11e9-800c-27e8af16da88.png)

The subscribe action works fine, which suggests it's not a problem with the config etc.

**Comment by aelvan** [comment]
This was due to a PHP 7.2 error, it has been fixed in 3.0.0, and backported to 2.0.5.
