### ISSUE TITLE
Change "list ID" to "audience ID"

### ISSUE THREAD

**Issue by nilsenpaul** [aelvan/mailchimp-subscribe-craft#77]
After having searched for the `List ID` in MailChimp for some time, I stumbled upon what they now call the `Audience ID`. Using this for the `listId` config setting, works.

According to [this](https://mailchimp.com/resources/introducing-your-new-audience-dashboard/), lists are now audiences. Hence the name change. Could you change this in your plugin, too?

**Comment by aelvan** [comment]
v3.0.0 is all audience.
