### ISSUE TITLE
Not working for checkbox group types

### ISSUE THREAD

**Issue by ben-callaway** [aelvan/mailchimp-subscribe-craft#80]
Fixed by: 

if ($group['type'] === 'radio' || $group['type'] === 'dropdown' || $group['type'] === 'checkboxes')

Also not working when submitting blank arrays, i.e. clear options fully.

**Comment by aelvan** [comment]
This was fixed in v3.0.0. Alot has changed in terms of interest groups, so make sure you read the changelog and new readme before updating.
