### ISSUE TITLE
Only subscribes successfully when no interest groups are passed through

### ISSUE THREAD

**Issue by icreatestuff** [aelvan/mailchimp-subscribe-craft#82]
I have the following form which subscribes perfectly when none of the interest groups are checked, but with any 1 or more of them ticked I get back a `400 Invalid Resource` error back from Mailchimp.

```twig
<form class="mailchimp-form js-mailchimp-form" action="" method="POST">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="mailchimp-subscribe/list/subscribe">

    {% if mailchimpSubscribe is defined %}
        {% if (not mailchimpSubscribe.success) and (mailchimpSubscribe.errorCode!='1000') %}
            <p>An error occured. Please try again.</p>
        {% endif %}
      
        {% if mailchimpSubscribe.success %}
            <p>Thank you for signing up!</p>
        {% endif %}
    {% endif %}
    
    <div class="form-field">
        <input type="text" name="mcvars[FNAME]" placeholder="First Name*" value="" required>
    </div>

    <div class="form-field">
        <input type="text" name="mcvars[LNAME]" placeholder="Last Name*" value="" required>
    </div>

    <div class="form-field">
        <input type="text" name="email" placeholder="Email Address*"  value="" required>
    </div>

    {% set interestGroups = craft.mailchimpSubscribe.getListInterestGroups(craft.config.listId) %}

    {% if interestGroups.success and (interestGroups.groups | length > 0) %}
        <fieldset>
            <legend>Please send me</legend>

            {% for group in interestGroups.groups %}
                {% if group.type=='checkboxes' %}
                    {% for interest in group.interests %}
                            <input type="checkbox" value="{{ interest.id }}" name="mcvars[interests][]" id="mailchimp-interests--{{ interest.id }}">
                            <label for="mailchimp-interests--{{ interest.id }}">{{ interest.name }}</label>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </fieldset>
    {% endif %}
    
    <button type="submit">Subscribe</button>
</form>
```
Example response data:

```json
{
    "success": false,
    "errorCode": 400,
    "message": "Invalid Resource",
    "values":{
        "email": "matt@*********.uk",
        "vars": {
            "FNAME": "Matt",
            "LNAME": "Jones",
            "interests": { 
                "93aaaa83bf": true,
                "516a251c0b": false,
                "251b30c2d0": false
            }
        }
    }
}
```

- Craft 3.1.29
- Mailchimp Subscribe Plugin 2.0.4
- PHP 7.2.1

Many thanks,
Matt

**Comment by icreatestuff** [comment]
Any ideas, anyone?

**Comment by aelvan** [comment]
Sounds like the interests group ids isn't from the same list/audience? I see that you send `craft.config.listId` as the parameter to the `getListInterestGroups` method. That's not how you access Mailchimp Subscribe's settings, so unless you have that variable in your general config too, it'll return `null`. 

You don't have to pass an id to that function if you want to use the one you have configured in your config file, so try just removing it. If you want to access the the listId from the settings, you do that with `craft.app.plugins.getPlugin('mailchimp-subscribe').getSettings().listId`.

**Comment by icreatestuff** [comment]
Thanks @aelvan for providing some things to try. As you suggested I changed how the `interestGroups` variable is set, to now use:

```
{% set interestGroups = craft.mailchimpSubscribe.getListInterestGroups() %}
```

This is bringing back all the correct groups for the correct list/audience, of which I'm only showing those that are of the 'checkbox' type. Still however I'm seeing an `Invalid Resource` error when trying to subscribe with any of the interest groups ticked. As before, when no groups are ticked, the form successfully subscribes me to the list.

It might be worth noting there are other interest groups for this list that I'm not showing in the form because they have the type of 'hidden' set in Mailchimp. Could this be causing an issue?

Is there anything else you can think of to try?
Many Thanks

**Comment by icreatestuff** [comment]
Just a quick follow up, I updated to v3.0.0 and tweaked the interest groups as describe in your updated examples and it's all working perfectly now. Thanks!
