### ISSUE TITLE
Add ability to not reset interests

### ISSUE THREAD

**Issue by davist11** [aelvan/mailchimp-subscribe-craft#83]
We have a site where there are multiple sign-up forms on different pages for different interests.

For example:
On the internships page, a user could sign up to be notified about internships (the internships interest). On the careers page, a user could sign up to be notified about careers (the careers interest).

The problem is that the interests are reset for the user each time they subscribe: https://github.com/aelvan/mailchimp-subscribe-craft/blob/a25ca18a4a56759f38a8184d2c7e3e89072bf9cf/src/services/MailchimpSubscribeService.php#L750-L757

Could the ability to **not** reset the interests on subscribe be added? Let me know if you think this would be valuable to add and if you have the bandwidth to add it. Alternatively, I could submit a PR if you would accept that type of change.

Thanks!

**Comment by aelvan** [comment]
I'm pretty sure it doesn't reset them unless you actually output an `<input type="hidden" value="" name="interests[{{ group.title }}]">` for the groups you want to keep as-is. Can you post your twig template code?

**Comment by gregkohn** [comment]
Hey, I picked up the ticket @davist11 was working on, so to follow up -- we aren't passing any extra hidden values. Here's the relevant code:

```twig
{% if interestGroups %}
  <div>
    {% for group in interestGroups if group.type == 'checkboxes' %}
      {% for interest in group.interests if interest.id == block.interestGroup %}
        <input type="hidden" value="{{ interest.id }}" name="interests[{{ group.title }}][]">
      {% endfor %}
    {% endfor %}
  </div>
{% endif %}
```

For some extra clarification, because MailChimp decided to name things terribly, we have multiple `Group`s within a single `Groups`. So in effect, one page may have a compiled input like
```
<input type="hidden" value="12345" name="interests[Email Lists][]">
```
while another is only passing a different `value`:
```
<input type="hidden" value="67890" name="interests[Email Lists][]">
```

Currently, filling out both forms with the same email unsubscribes the user from the first group.

**Comment by martijnvanonz** [comment]
Hello, 

Any updates on this?

**Comment by davist11** [comment]
I have a PR that I could submit with my solution, which entailed using a hidden input to determine whether the interests should be reset or not.
