### ISSUE TITLE
Can not be added into an Audience when set 'doubleOptIn' to false

### ISSUE THREAD

**Issue by ryanrunqin** [aelvan/mailchimp-subscribe-craft#85]
When set 'doubleOptIn' => true, it works fine. I can join the audience after the confirmation email. But when 'doubleOptIn' is false, my (another test) email can not be added to the audience. I used the sample code which has redirection and audienceId only.

Any ideas? 
Thank you~

**Comment by aelvan** [comment]
Still works for me. Have you checked for error messages in your logs/debug toolbar? Sure the test email hasn't been deleted from your list. Try removing redirection and dumping the mailchimpSubscribe object, that should have complete the response from Mailchimp, which should give you an idea why it's not working.

```
{% if mailchimpSubscribe is defined %}
<pre>
{{ dump(mailchimpSubscribe ?? null) }}
</pre>
{% endif %}
```
