### ISSUE TITLE
Multiple Lists in 3.x

### ISSUE THREAD

**Issue by ademers** [aelvan/mailchimp-subscribe-craft#86]
In 2.x I was allowing users to subscribe to multiple lists via `<input type="hidden" name="lid" value="2fd6ec09cf|5fe66521c0">`. Apparently this is no longer possible in 3.x as per https://github.com/aelvan/mailchimp-subscribe-craft/blob/craft3/CHANGELOG.md#removed. How can I reinstate this in 3.x? In a custom module, can I add:

```
$msPlugin = Craft::$app->plugins->getPlugin('mailchimp-subscribe');

if ($msPlugin && $msPlugin instanceof \aelvan\mailchimpsubscribe\MailchimpSubscribe) {
    $msPlugin->mailchimpSubscribe->subscribe('my_email@domain.com', '2a34d0978q');
}
```
and replace `2a34d0978q` with an array? I'm a novice plugin/module dev., so this isn't obvious to me. I appreciate your help. Thanks!

**Comment by aelvan** [comment]
No, you'd have to do two consecutive calls to the `subscribe` method:

```
$msPlugin = Craft::$app->plugins->getPlugin('mailchimp-subscribe');

if ($msPlugin && $msPlugin instanceof \aelvan\mailchimpsubscribe\MailchimpSubscribe) {
    $msPlugin->mailchimpSubscribe->subscribe('my_email@domain.com', '2a34d0978q');
    $msPlugin->mailchimpSubscribe->subscribe('my_email@domain.com', '5fe66521c0');
}
```

Hope that helps.
