### ISSUE TITLE
Redirect on error

### ISSUE THREAD

**Issue by paulgoodfield** [aelvan/mailchimp-subscribe-craft#91]
Would there be any chance of adding the ability to specify a redirect for when `subscribeResponse.success == false`?

It could work in a similar way to adding the `{{ redirectInput('foo/bar') }}` field - add a new hidden field like `<input type="hidden" name="redirectError" value="{{ 'foo/bar#signup-form'|hash }}">`.

My scenario: I have a page on a website (**/get-email-updates**) that has a sign-up form that is halfway down the page. Currently, if the user fills out and submits the form but the subscribeResponse returns an error, the user will just get redirected back to the same url, which will return them back to the top of the page. Ideally I want to specify that if there is an error, they should get redirected back to **/get-email-updates#signup-form**, which will automatically scroll the page back down to the form (the form has id="signup-form").

**Comment by aelvan** [comment]
You can already do this by adding the anchor to the forms action parameter, ie:

`<form action="#lorem" method="post">`
