### ISSUE TITLE
Interest groups not being populated

### ISSUE THREAD

**Issue by iamkeir** [aelvan/mailchimp-subscribe-craft#92]
Hey folks - thanks @aelvan for an ace plugin.

I am able to successfully subscribe a user via my custom module code with all data except for Interest Groups.

```
$result = $msPlugin->mailchimpSubscribe->subscribe($user['email'], $listID, [
  'email_type' => 'html',
  'language' => 'en',
  'vip' => false,
  'tags' => $userTags,
  'merge_fields' => [
    'FNAME' => $user['firstName'],
    'LNAME' => $user['lastName']
  ],
  'interests' => [   
    '1bac2206ac' => true,
    'b56f9fbb58' => true
  ],
]);
``` 
I have triple-checked my interest group IDs via the MailChimp API Playground but for some reason this particular piece of the data is being ignored.

Am I missing something really obvious?

**Comment by iamkeir** [comment]
I moved `interests` _above_ `merge_fields` and it seemed to work...

**Comment by iamkeir** [comment]
I spoke to soon - it is setting both to true/1, even if one is false/0...?

**Comment by iamkeir** [comment]
This is the data being sent/received - it is being supplied correctly but coming back as if both are checked. (Some data omitted for privacy)

**Supplied:**
```
aelvan\mailchimpsubscribe\models\SubscribeResponse Object
(
    [action] => subscribe
    [success] => 1
    [errorCode] => 200
    [message] => Subscribed successfully
    [values] => Array
        (            
            [interests] => Array
                (
                    [1bac2206ac] => 0
                    [b56f9fbb58] => 1
                )
        )
)  
```
**Result from  `[response] => Illuminate\Support\Collection Object`**
```
[interests] => stdClass Object
  (
    [1bac2206ac] => 1 // ***THIS SHOULD BE 0/FALSE***
    [b56f9fbb58] => 1
  )
```

**Comment by bkrsmanovic** [comment]
@iamkeir maybe unrelated issue, but before, when you had some of interest group subscribed (for example with checkboxes), lets say these are options:
1
2
**3**
**4**
5

3 and 4 were subscribed ones. And before, if same user subscribes to new form with single value number 5, it was concat to current ones and user would be subscribed to 3 4 and 5.

Now, it removes 3 and 4 and keeps only 5. Maybe whole separated issue but might give you some reasoning.

Do you have any idea regarding this why it might occur?

**Comment by iamkeir** [comment]
@bkrsmanovic I don't I'm afraid - that's a separate issue. I'd make a new github issue for that.

**Comment by aelvan** [comment]
Interests is a nested array where the first level is the groups title, and the second level are the id's that are to be set to true, like this:

```
'interests' => [
    'Job position' => [
        '3ba98a1818'
    ],
    'My interests' => [
        '517e7629d5',
        '15128d2dcf'
    ]
]
```
