### ISSUE TITLE
Craft::parseEnv

### ISSUE THREAD

**Issue by jonathan-brown** [aelvan/mailchimp-subscribe-craft#94]
Has anyone had any issues with Craft::parseEnv on the both 'apiKey' and 'audienceId' ? 

I get the following on a basic form submission 

Call to undefined method Craft::parseEnv()

**Comment by gmhenderson** [comment]
Yes, I just experienced this because `Craft::parseEnv()` wasn't added until Craft 3.1. The requirements for this plugin should be updated accordingly.
