### ISSUE TITLE
JSON response not returned

### ISSUE THREAD

**Issue by timmyomahony** [aelvan/mailchimp-subscribe-craft#96]
The docs say:

> Returns JSON if the request was an ajax request/has the right headers.

but it's not clear what those headers are. I'm using the following code:

```
      let jsonString = // ...
      let xhr = new XMLHttpRequest();
      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) {
           //...
        } else {
          // ...
        }
      };
      xhr.open("POST", "", true);
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.send(jsonString);
```

My request is XHR, it headers contain `application/json` as well as the relevent `action`, `email` and CSRF token but the response is HTML.

**Comment by aelvan** [comment]
Not even closely related to Mailchimp Subscribe or Craft, but... to set which content types a client accepts, set [the Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept). Content-Type is for setting [the type of content the client sends](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type).

**Comment by timmyomahony** [comment]
Thanks for the help but this wasn't really necesseary:

> Not even closely related to Mailchimp Subscribe or Craft, but...

**Comment by aelvan** [comment]
Yeah, I know, sometimes I get tired. Sorry about that.

**Comment by timmyomahony** [comment]
Here's a rough snippet for anyone who comes across this in the future:

```js
submitForm() {
  ...
  var form = document.querySelector("form");
  var json = this.toJSONString(form);
  var xhr = new XMLHttpRequest();
  xhr.onload = () => {
    if (xhr.status >= 200 && xhr.status < 300) {
     ...
    } else {
      alert("There was an unexpected error");
    }
    ...
  };
  xhr.open("POST", "/actions/mailchimp-subscribe/audience/subscribe", true);
  xhr.setRequestHeader("Content-Type", "application/json");
  xhr.setRequestHeader("Accept", "application/json");
  xhr.send(json);
  }
}

toJSONString(form) {
  var obj = {};
  var elements = form.querySelectorAll("input, select, textarea");
  for (var i = 0; i < elements.length; ++i) {
    var element = elements[i];
    var name = element.name;
    var value = element.value;

    if (name) {
      obj[name] = value;
    }
  }
  return JSON.stringify(obj);
}
```

**Comment by masiorama** [comment]
@aelvan does this work with the latest version?
I just tried to on the last version and it does not work (on xhr panel i get error 500 and `{"error":"Page not found."}`), while on another project I have version 3.0.3 and it does work as expected.
Is this not supported anymore?
Thanks!
