### ISSUE TITLE
404 template not found after submit

### ISSUE THREAD

**Issue by anoukaveresch** [aelvan/mailchimp-subscribe-craft#97]
When I submit the signup form, I get the error "Template not found: mailchimp-subscribe/audience/subscribe".

This is my form:

`<form class="newsletter-form" action="mailchimp-subscribe/audience/subscribe" method="post">`
    `            {{ csrfInput() }}
                <input type="hidden" name="tags" value="Website aanmelding nieuwsbrief">

                {% set subscribeResponse = mailchimpSubscribe is defined and mailchimpSubscribe.action == 'subscribe' ? mailchimpSubscribe : null %}

                <div>
                    {% if subscribeResponse %}
                        {% if subscribeResponse.success %}
                            <p>U bent ingeschreven</p>
                        {% else %}
                            <p>Er heeft zich een fout voorgedaan: {{ subscribeResponse.message }}</p>
                        {% endif %}
                    {% endif %}
                </div>

                <div class="g-cols:2">
                    <div>
                        <fieldset class="form-group || c-footer__form-input">
                            <label for="emailInput" class="u-sr-only {% if subscribeResponse and subscribeResponse.errorCode=='1000' %}error{% endif %}">Email</label>
                            <input type="text" id="emailInput" name="email" class="form-control || c-footer__form-field" placeholder="Jouw e-mailadres" {% if subscribeResponse and not subscribeResponse.success %}value="{{ subscribeResponse.values.email ?? '' }}"{% endif %} required>
                        </fieldset>
                    </div>

                    <div>
                        <fieldset>
                            <button type="submit" class="[ c-btn c-btn--primary ] c-footer__form-btn u-font-weight-bold">Aanmelden</button>
                        </fieldset>
                    </div>
                </div>
            </form>`

I don't understand what's going on and why I get this error. Can you help me?

**Comment by aelvan** [comment]
That's not how you submit to an action in Craft. The action parameter on the form tag should be empty, and there should be a hidden input with name `action`. Please refer to the examples in the docs.
