### ISSUE TITLE
ComposerAutoloader not found error on install – Craft 2

### ISSUE THREAD

**Issue by andrewlarner** [aelvan/mailchimp-subscribe-craft#99]
I'm using Craft v2.9.2, and trying to install the 1.1.7 version of the MailChimp Subscribe plugin. Unfortunately, I run into the following error:

`Class 'ComposerAutoloaderInit1824f24187c70f41aece30feee75b989' not found`

After attempting to install from the Admin/Plugins section. Is there anyway I can fix this? I'm running MAMP Pro, PHP version 7.2.1 and my Composer version is 1.10.6.

Appreciate any help, thanks!

![mailchimp-subscribe-error-190520](https://user-images.githubusercontent.com/10127953/82322726-e4410300-99ce-11ea-809f-4d16a54921bd.jpg)

**Comment by andrewlarner** [comment]
Running `composer install`, locally with Terminal, inside the `mailchimpsubscribe` plugin folder fixed this. If anyone runs into the same issue.

**Comment by outline4** [comment]
Hi, I am having the same problem!  
But I cannot SSH on this project.  

Is there another way for fixing this? 

Cheers  
Stefan

**Comment by aelvan** [comment]
Seems like the autoloader files in PR #78 was incomplete. I've run composer update and pushed version 1.1.8.

**Comment by outline4** [comment]
Thanks a lot!
